"""empty message

Revision ID: 266c1c3f29b7
Revises: 
Create Date: 2017-12-14 12:16:34.335701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266c1c3f29b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(length=80), nullable=True))
    op.drop_index('email', table_name='article')
    op.drop_index('username', table_name='article')
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.create_index('username', 'article', ['title'], unique=True)
    op.create_index('email', 'article', ['content'], unique=True)
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
